<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('countries')->delete();

        \DB::table('countries')->insert(array (
            0 =>
            array (
                'id' => 1,
                'code' => 'AF',
                'name' => 'Afghanistan',
                'phone_code' => 93,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 =>
            array (
                'id' => 2,
                'code' => 'AL',
                'name' => 'Albania',
                'phone_code' => 355,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 =>
            array (
                'id' => 3,
                'code' => 'DZ',
                'name' => 'Algeria',
                'phone_code' => 213,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 =>
            array (
                'id' => 4,
                'code' => 'AS',
                'name' => 'American Samoa',
                'phone_code' => 1684,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 =>
            array (
                'id' => 5,
                'code' => 'AD',
                'name' => 'Andorra',
                'phone_code' => 376,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 =>
            array (
                'id' => 6,
                'code' => 'AO',
                'name' => 'Angola',
                'phone_code' => 244,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 =>
            array (
                'id' => 7,
                'code' => 'AI',
                'name' => 'Anguilla',
                'phone_code' => 1264,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 =>
            array (
                'id' => 8,
                'code' => 'AQ',
                'name' => 'Antarctica',
                'phone_code' => 0,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 =>
            array (
                'id' => 9,
                'code' => 'AG',
                'name' => 'Antigua And Barbuda',
                'phone_code' => 1268,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 =>
            array (
                'id' => 10,
                'code' => 'AR',
                'name' => 'Argentina',
                'phone_code' => 54,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 =>
            array (
                'id' => 11,
                'code' => 'AM',
                'name' => 'Armenia',
                'phone_code' => 374,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 =>
            array (
                'id' => 12,
                'code' => 'AW',
                'name' => 'Aruba',
                'phone_code' => 297,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 =>
            array (
                'id' => 13,
                'code' => 'AU',
                'name' => 'Australia',
                'phone_code' => 61,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 =>
            array (
                'id' => 14,
                'code' => 'AT',
                'name' => 'Austria',
                'phone_code' => 43,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 =>
            array (
                'id' => 15,
                'code' => 'AZ',
                'name' => 'Azerbaijan',
                'phone_code' => 994,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 =>
            array (
                'id' => 16,
                'code' => 'BS',
                'name' => 'Bahamas The',
                'phone_code' => 1242,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 =>
            array (
                'id' => 17,
                'code' => 'BH',
                'name' => 'Bahrain',
                'phone_code' => 973,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 =>
            array (
                'id' => 18,
                'code' => 'BD',
                'name' => 'Bangladesh',
                'phone_code' => 880,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 =>
            array (
                'id' => 19,
                'code' => 'BB',
                'name' => 'Barbados',
                'phone_code' => 1246,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 =>
            array (
                'id' => 20,
                'code' => 'BY',
                'name' => 'Belarus',
                'phone_code' => 375,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 =>
            array (
                'id' => 21,
                'code' => 'BE',
                'name' => 'Belgium',
                'phone_code' => 32,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 =>
            array (
                'id' => 22,
                'code' => 'BZ',
                'name' => 'Belize',
                'phone_code' => 501,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 =>
            array (
                'id' => 23,
                'code' => 'BJ',
                'name' => 'Benin',
                'phone_code' => 229,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 =>
            array (
                'id' => 24,
                'code' => 'BM',
                'name' => 'Bermuda',
                'phone_code' => 1441,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 =>
            array (
                'id' => 25,
                'code' => 'BT',
                'name' => 'Bhutan',
                'phone_code' => 975,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 =>
            array (
                'id' => 26,
                'code' => 'BO',
                'name' => 'Bolivia',
                'phone_code' => 591,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 =>
            array (
                'id' => 27,
                'code' => 'BA',
                'name' => 'Bosnia and Herzegovina',
                'phone_code' => 387,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 =>
            array (
                'id' => 28,
                'code' => 'BW',
                'name' => 'Botswana',
                'phone_code' => 267,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 =>
            array (
                'id' => 29,
                'code' => 'BV',
                'name' => 'Bouvet Island',
                'phone_code' => 0,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 =>
            array (
                'id' => 30,
                'code' => 'BR',
                'name' => 'Brazil',
                'phone_code' => 55,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 =>
            array (
                'id' => 31,
                'code' => 'IO',
                'name' => 'British Indian Ocean Territory',
                'phone_code' => 246,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 =>
            array (
                'id' => 32,
                'code' => 'BN',
                'name' => 'Brunei',
                'phone_code' => 673,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 =>
            array (
                'id' => 33,
                'code' => 'BG',
                'name' => 'Bulgaria',
                'phone_code' => 359,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 =>
            array (
                'id' => 34,
                'code' => 'BF',
                'name' => 'Burkina Faso',
                'phone_code' => 226,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 =>
            array (
                'id' => 35,
                'code' => 'BI',
                'name' => 'Burundi',
                'phone_code' => 257,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 =>
            array (
                'id' => 36,
                'code' => 'KH',
                'name' => 'Cambodia',
                'phone_code' => 855,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 =>
            array (
                'id' => 37,
                'code' => 'CM',
                'name' => 'Cameroon',
                'phone_code' => 237,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            37 =>
            array (
                'id' => 38,
                'code' => 'CA',
                'name' => 'Canada',
                'phone_code' => 1,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 =>
            array (
                'id' => 39,
                'code' => 'CV',
                'name' => 'Cape Verde',
                'phone_code' => 238,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            39 =>
            array (
                'id' => 40,
                'code' => 'KY',
                'name' => 'Cayman Islands',
                'phone_code' => 1345,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            40 =>
            array (
                'id' => 41,
                'code' => 'CF',
                'name' => 'Central African Republic',
                'phone_code' => 236,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            41 =>
            array (
                'id' => 42,
                'code' => 'TD',
                'name' => 'Chad',
                'phone_code' => 235,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            42 =>
            array (
                'id' => 43,
                'code' => 'CL',
                'name' => 'Chile',
                'phone_code' => 56,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            43 =>
            array (
                'id' => 44,
                'code' => 'CN',
                'name' => 'China',
                'phone_code' => 86,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            44 =>
            array (
                'id' => 45,
                'code' => 'CX',
                'name' => 'Christmas Island',
                'phone_code' => 61,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            45 =>
            array (
                'id' => 46,
                'code' => 'CC',
            'name' => 'Cocos (Keeling) Islands',
                'phone_code' => 672,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            46 =>
            array (
                'id' => 47,
                'code' => 'CO',
                'name' => 'Colombia',
                'phone_code' => 57,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            47 =>
            array (
                'id' => 48,
                'code' => 'KM',
                'name' => 'Comoros',
                'phone_code' => 269,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            48 =>
            array (
                'id' => 49,
                'code' => 'CG',
                'name' => 'Congo',
                'phone_code' => 242,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            49 =>
            array (
                'id' => 50,
                'code' => 'CD',
                'name' => 'Congo The Democratic Republic Of The',
                'phone_code' => 242,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            50 =>
            array (
                'id' => 51,
                'code' => 'CK',
                'name' => 'Cook Islands',
                'phone_code' => 682,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            51 =>
            array (
                'id' => 52,
                'code' => 'CR',
                'name' => 'Costa Rica',
                'phone_code' => 506,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            52 =>
            array (
                'id' => 53,
                'code' => 'CI',
            'name' => 'Cote D Ivoire (Ivory Coast)',
                'phone_code' => 225,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            53 =>
            array (
                'id' => 54,
                'code' => 'HR',
            'name' => 'Croatia (Hrvatska)',
                'phone_code' => 385,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            54 =>
            array (
                'id' => 55,
                'code' => 'CU',
                'name' => 'Cuba',
                'phone_code' => 53,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            55 =>
            array (
                'id' => 56,
                'code' => 'CY',
                'name' => 'Cyprus',
                'phone_code' => 357,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            56 =>
            array (
                'id' => 57,
                'code' => 'CZ',
                'name' => 'Czech Republic',
                'phone_code' => 420,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            57 =>
            array (
                'id' => 58,
                'code' => 'DK',
                'name' => 'Denmark',
                'phone_code' => 45,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            58 =>
            array (
                'id' => 59,
                'code' => 'DJ',
                'name' => 'Djibouti',
                'phone_code' => 253,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            59 =>
            array (
                'id' => 60,
                'code' => 'DM',
                'name' => 'Dominica',
                'phone_code' => 1767,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            60 =>
            array (
                'id' => 61,
                'code' => 'DO',
                'name' => 'Dominican Republic',
                'phone_code' => 1809,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            61 =>
            array (
                'id' => 62,
                'code' => 'TP',
                'name' => 'East Timor',
                'phone_code' => 670,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            62 =>
            array (
                'id' => 63,
                'code' => 'EC',
                'name' => 'Ecuador',
                'phone_code' => 593,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            63 =>
            array (
                'id' => 64,
                'code' => 'EG',
                'name' => 'Egypt',
                'phone_code' => 20,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            64 =>
            array (
                'id' => 65,
                'code' => 'SV',
                'name' => 'El Salvador',
                'phone_code' => 503,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            65 =>
            array (
                'id' => 66,
                'code' => 'GQ',
                'name' => 'Equatorial Guinea',
                'phone_code' => 240,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            66 =>
            array (
                'id' => 67,
                'code' => 'ER',
                'name' => 'Eritrea',
                'phone_code' => 291,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            67 =>
            array (
                'id' => 68,
                'code' => 'EE',
                'name' => 'Estonia',
                'phone_code' => 372,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            68 =>
            array (
                'id' => 69,
                'code' => 'ET',
                'name' => 'Ethiopia',
                'phone_code' => 251,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            69 =>
            array (
                'id' => 70,
                'code' => 'XA',
                'name' => 'External Territories of Australia',
                'phone_code' => 61,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            70 =>
            array (
                'id' => 71,
                'code' => 'FK',
                'name' => 'Falkland Islands',
                'phone_code' => 500,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            71 =>
            array (
                'id' => 72,
                'code' => 'FO',
                'name' => 'Faroe Islands',
                'phone_code' => 298,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            72 =>
            array (
                'id' => 73,
                'code' => 'FJ',
                'name' => 'Fiji Islands',
                'phone_code' => 679,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            73 =>
            array (
                'id' => 74,
                'code' => 'FI',
                'name' => 'Finland',
                'phone_code' => 358,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            74 =>
            array (
                'id' => 75,
                'code' => 'FR',
                'name' => 'France',
                'phone_code' => 33,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            75 =>
            array (
                'id' => 76,
                'code' => 'GF',
                'name' => 'French Guiana',
                'phone_code' => 594,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            76 =>
            array (
                'id' => 77,
                'code' => 'PF',
                'name' => 'French Polynesia',
                'phone_code' => 689,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            77 =>
            array (
                'id' => 78,
                'code' => 'TF',
                'name' => 'French Southern Territories',
                'phone_code' => 0,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            78 =>
            array (
                'id' => 79,
                'code' => 'GA',
                'name' => 'Gabon',
                'phone_code' => 241,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            79 =>
            array (
                'id' => 80,
                'code' => 'GM',
                'name' => 'Gambia The',
                'phone_code' => 220,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            80 =>
            array (
                'id' => 81,
                'code' => 'GE',
                'name' => 'Georgia',
                'phone_code' => 995,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            81 =>
            array (
                'id' => 82,
                'code' => 'DE',
                'name' => 'Germany',
                'phone_code' => 49,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            82 =>
            array (
                'id' => 83,
                'code' => 'GH',
                'name' => 'Ghana',
                'phone_code' => 233,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            83 =>
            array (
                'id' => 84,
                'code' => 'GI',
                'name' => 'Gibraltar',
                'phone_code' => 350,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            84 =>
            array (
                'id' => 85,
                'code' => 'GR',
                'name' => 'Greece',
                'phone_code' => 30,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            85 =>
            array (
                'id' => 86,
                'code' => 'GL',
                'name' => 'Greenland',
                'phone_code' => 299,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            86 =>
            array (
                'id' => 87,
                'code' => 'GD',
                'name' => 'Grenada',
                'phone_code' => 1473,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            87 =>
            array (
                'id' => 88,
                'code' => 'GP',
                'name' => 'Guadeloupe',
                'phone_code' => 590,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            88 =>
            array (
                'id' => 89,
                'code' => 'GU',
                'name' => 'Guam',
                'phone_code' => 1671,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            89 =>
            array (
                'id' => 90,
                'code' => 'GT',
                'name' => 'Guatemala',
                'phone_code' => 502,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            90 =>
            array (
                'id' => 91,
                'code' => 'XU',
                'name' => 'Guernsey and Alderney',
                'phone_code' => 44,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            91 =>
            array (
                'id' => 92,
                'code' => 'GN',
                'name' => 'Guinea',
                'phone_code' => 224,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            92 =>
            array (
                'id' => 93,
                'code' => 'GW',
                'name' => 'Guinea-Bissau',
                'phone_code' => 245,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            93 =>
            array (
                'id' => 94,
                'code' => 'GY',
                'name' => 'Guyana',
                'phone_code' => 592,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            94 =>
            array (
                'id' => 95,
                'code' => 'HT',
                'name' => 'Haiti',
                'phone_code' => 509,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            95 =>
            array (
                'id' => 96,
                'code' => 'HM',
                'name' => 'Heard and McDonald Islands',
                'phone_code' => 0,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            96 =>
            array (
                'id' => 97,
                'code' => 'HN',
                'name' => 'Honduras',
                'phone_code' => 504,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            97 =>
            array (
                'id' => 98,
                'code' => 'HK',
                'name' => 'Hong Kong S.A.R.',
                'phone_code' => 852,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            98 =>
            array (
                'id' => 99,
                'code' => 'HU',
                'name' => 'Hungary',
                'phone_code' => 36,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            99 =>
            array (
                'id' => 100,
                'code' => 'IS',
                'name' => 'Iceland',
                'phone_code' => 354,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            100 =>
            array (
                'id' => 101,
                'code' => 'IN',
                'name' => 'India',
                'phone_code' => 91,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            101 =>
            array (
                'id' => 102,
                'code' => 'ID',
                'name' => 'Indonesia',
                'phone_code' => 62,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            102 =>
            array (
                'id' => 103,
                'code' => 'IR',
                'name' => 'Iran',
                'phone_code' => 98,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            103 =>
            array (
                'id' => 104,
                'code' => 'IQ',
                'name' => 'Iraq',
                'phone_code' => 964,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            104 =>
            array (
                'id' => 105,
                'code' => 'IE',
                'name' => 'Ireland',
                'phone_code' => 353,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            105 =>
            array (
                'id' => 106,
                'code' => 'IL',
                'name' => 'Israel',
                'phone_code' => 972,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            106 =>
            array (
                'id' => 107,
                'code' => 'IT',
                'name' => 'Italy',
                'phone_code' => 39,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            107 =>
            array (
                'id' => 108,
                'code' => 'JM',
                'name' => 'Jamaica',
                'phone_code' => 1876,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            108 =>
            array (
                'id' => 109,
                'code' => 'JP',
                'name' => 'Japan',
                'phone_code' => 81,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            109 =>
            array (
                'id' => 110,
                'code' => 'XJ',
                'name' => 'Jersey',
                'phone_code' => 44,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            110 =>
            array (
                'id' => 111,
                'code' => 'JO',
                'name' => 'Jordan',
                'phone_code' => 962,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            111 =>
            array (
                'id' => 112,
                'code' => 'KZ',
                'name' => 'Kazakhstan',
                'phone_code' => 7,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            112 =>
            array (
                'id' => 113,
                'code' => 'KE',
                'name' => 'Kenya',
                'phone_code' => 254,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            113 =>
            array (
                'id' => 114,
                'code' => 'KI',
                'name' => 'Kiribati',
                'phone_code' => 686,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            114 =>
            array (
                'id' => 115,
                'code' => 'KP',
                'name' => 'Korea North',
                'phone_code' => 850,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            115 =>
            array (
                'id' => 116,
                'code' => 'KR',
                'name' => 'Korea South',
                'phone_code' => 82,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            116 =>
            array (
                'id' => 117,
                'code' => 'KW',
                'name' => 'Kuwait',
                'phone_code' => 965,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            117 =>
            array (
                'id' => 118,
                'code' => 'KG',
                'name' => 'Kyrgyzstan',
                'phone_code' => 996,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            118 =>
            array (
                'id' => 119,
                'code' => 'LA',
                'name' => 'Laos',
                'phone_code' => 856,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            119 =>
            array (
                'id' => 120,
                'code' => 'LV',
                'name' => 'Latvia',
                'phone_code' => 371,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            120 =>
            array (
                'id' => 121,
                'code' => 'LB',
                'name' => 'Lebanon',
                'phone_code' => 961,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            121 =>
            array (
                'id' => 122,
                'code' => 'LS',
                'name' => 'Lesotho',
                'phone_code' => 266,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            122 =>
            array (
                'id' => 123,
                'code' => 'LR',
                'name' => 'Liberia',
                'phone_code' => 231,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            123 =>
            array (
                'id' => 124,
                'code' => 'LY',
                'name' => 'Libya',
                'phone_code' => 218,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            124 =>
            array (
                'id' => 125,
                'code' => 'LI',
                'name' => 'Liechtenstein',
                'phone_code' => 423,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            125 =>
            array (
                'id' => 126,
                'code' => 'LT',
                'name' => 'Lithuania',
                'phone_code' => 370,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            126 =>
            array (
                'id' => 127,
                'code' => 'LU',
                'name' => 'Luxembourg',
                'phone_code' => 352,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            127 =>
            array (
                'id' => 128,
                'code' => 'MO',
                'name' => 'Macau S.A.R.',
                'phone_code' => 853,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            128 =>
            array (
                'id' => 129,
                'code' => 'MK',
                'name' => 'Macedonia',
                'phone_code' => 389,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            129 =>
            array (
                'id' => 130,
                'code' => 'MG',
                'name' => 'Madagascar',
                'phone_code' => 261,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            130 =>
            array (
                'id' => 131,
                'code' => 'MW',
                'name' => 'Malawi',
                'phone_code' => 265,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            131 =>
            array (
                'id' => 132,
                'code' => 'MY',
                'name' => 'Malaysia',
                'phone_code' => 60,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            132 =>
            array (
                'id' => 133,
                'code' => 'MV',
                'name' => 'Maldives',
                'phone_code' => 960,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            133 =>
            array (
                'id' => 134,
                'code' => 'ML',
                'name' => 'Mali',
                'phone_code' => 223,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            134 =>
            array (
                'id' => 135,
                'code' => 'MT',
                'name' => 'Malta',
                'phone_code' => 356,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            135 =>
            array (
                'id' => 136,
                'code' => 'XM',
            'name' => 'Man (Isle of)',
                'phone_code' => 44,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            136 =>
            array (
                'id' => 137,
                'code' => 'MH',
                'name' => 'Marshall Islands',
                'phone_code' => 692,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            137 =>
            array (
                'id' => 138,
                'code' => 'MQ',
                'name' => 'Martinique',
                'phone_code' => 596,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            138 =>
            array (
                'id' => 139,
                'code' => 'MR',
                'name' => 'Mauritania',
                'phone_code' => 222,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            139 =>
            array (
                'id' => 140,
                'code' => 'MU',
                'name' => 'Mauritius',
                'phone_code' => 230,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            140 =>
            array (
                'id' => 141,
                'code' => 'YT',
                'name' => 'Mayotte',
                'phone_code' => 269,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            141 =>
            array (
                'id' => 142,
                'code' => 'MX',
                'name' => 'Mexico',
                'phone_code' => 52,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            142 =>
            array (
                'id' => 143,
                'code' => 'FM',
                'name' => 'Micronesia',
                'phone_code' => 691,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            143 =>
            array (
                'id' => 144,
                'code' => 'MD',
                'name' => 'Moldova',
                'phone_code' => 373,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            144 =>
            array (
                'id' => 145,
                'code' => 'MC',
                'name' => 'Monaco',
                'phone_code' => 377,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            145 =>
            array (
                'id' => 146,
                'code' => 'MN',
                'name' => 'Mongolia',
                'phone_code' => 976,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            146 =>
            array (
                'id' => 147,
                'code' => 'MS',
                'name' => 'Montserrat',
                'phone_code' => 1664,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            147 =>
            array (
                'id' => 148,
                'code' => 'MA',
                'name' => 'Morocco',
                'phone_code' => 212,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            148 =>
            array (
                'id' => 149,
                'code' => 'MZ',
                'name' => 'Mozambique',
                'phone_code' => 258,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            149 =>
            array (
                'id' => 150,
                'code' => 'MM',
                'name' => 'Myanmar',
                'phone_code' => 95,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            150 =>
            array (
                'id' => 151,
                'code' => 'NA',
                'name' => 'Namibia',
                'phone_code' => 264,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            151 =>
            array (
                'id' => 152,
                'code' => 'NR',
                'name' => 'Nauru',
                'phone_code' => 674,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            152 =>
            array (
                'id' => 153,
                'code' => 'NP',
                'name' => 'Nepal',
                'phone_code' => 977,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            153 =>
            array (
                'id' => 154,
                'code' => 'AN',
                'name' => 'Netherlands Antilles',
                'phone_code' => 599,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            154 =>
            array (
                'id' => 155,
                'code' => 'NL',
                'name' => 'Netherlands The',
                'phone_code' => 31,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            155 =>
            array (
                'id' => 156,
                'code' => 'NC',
                'name' => 'New Caledonia',
                'phone_code' => 687,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            156 =>
            array (
                'id' => 157,
                'code' => 'NZ',
                'name' => 'New Zealand',
                'phone_code' => 64,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            157 =>
            array (
                'id' => 158,
                'code' => 'NI',
                'name' => 'Nicaragua',
                'phone_code' => 505,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            158 =>
            array (
                'id' => 159,
                'code' => 'NE',
                'name' => 'Niger',
                'phone_code' => 227,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            159 =>
            array (
                'id' => 160,
                'code' => 'NG',
                'name' => 'Nigeria',
                'phone_code' => 234,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            160 =>
            array (
                'id' => 161,
                'code' => 'NU',
                'name' => 'Niue',
                'phone_code' => 683,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            161 =>
            array (
                'id' => 162,
                'code' => 'NF',
                'name' => 'Norfolk Island',
                'phone_code' => 672,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            162 =>
            array (
                'id' => 163,
                'code' => 'MP',
                'name' => 'Northern Mariana Islands',
                'phone_code' => 1670,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            163 =>
            array (
                'id' => 164,
                'code' => 'NO',
                'name' => 'Norway',
                'phone_code' => 47,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            164 =>
            array (
                'id' => 165,
                'code' => 'OM',
                'name' => 'Oman',
                'phone_code' => 968,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            165 =>
            array (
                'id' => 166,
                'code' => 'PK',
                'name' => 'Pakistan',
                'phone_code' => 92,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            166 =>
            array (
                'id' => 167,
                'code' => 'PW',
                'name' => 'Palau',
                'phone_code' => 680,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            167 =>
            array (
                'id' => 168,
                'code' => 'PS',
                'name' => 'Palestinian Territory Occupied',
                'phone_code' => 970,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            168 =>
            array (
                'id' => 169,
                'code' => 'PA',
                'name' => 'Panama',
                'phone_code' => 507,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            169 =>
            array (
                'id' => 170,
                'code' => 'PG',
                'name' => 'Papua new Guinea',
                'phone_code' => 675,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            170 =>
            array (
                'id' => 171,
                'code' => 'PY',
                'name' => 'Paraguay',
                'phone_code' => 595,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            171 =>
            array (
                'id' => 172,
                'code' => 'PE',
                'name' => 'Peru',
                'phone_code' => 51,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            172 =>
            array (
                'id' => 173,
                'code' => 'PH',
                'name' => 'Philippines',
                'phone_code' => 63,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            173 =>
            array (
                'id' => 174,
                'code' => 'PN',
                'name' => 'Pitcairn Island',
                'phone_code' => 0,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            174 =>
            array (
                'id' => 175,
                'code' => 'PL',
                'name' => 'Poland',
                'phone_code' => 48,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            175 =>
            array (
                'id' => 176,
                'code' => 'PT',
                'name' => 'Portugal',
                'phone_code' => 351,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            176 =>
            array (
                'id' => 177,
                'code' => 'PR',
                'name' => 'Puerto Rico',
                'phone_code' => 1787,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            177 =>
            array (
                'id' => 178,
                'code' => 'QA',
                'name' => 'Qatar',
                'phone_code' => 974,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            178 =>
            array (
                'id' => 179,
                'code' => 'RE',
                'name' => 'Reunion',
                'phone_code' => 262,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            179 =>
            array (
                'id' => 180,
                'code' => 'RO',
                'name' => 'Romania',
                'phone_code' => 40,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            180 =>
            array (
                'id' => 181,
                'code' => 'RU',
                'name' => 'Russia',
                'phone_code' => 70,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            181 =>
            array (
                'id' => 182,
                'code' => 'RW',
                'name' => 'Rwanda',
                'phone_code' => 250,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            182 =>
            array (
                'id' => 183,
                'code' => 'SH',
                'name' => 'Saint Helena',
                'phone_code' => 290,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            183 =>
            array (
                'id' => 184,
                'code' => 'KN',
                'name' => 'Saint Kitts And Nevis',
                'phone_code' => 1869,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            184 =>
            array (
                'id' => 185,
                'code' => 'LC',
                'name' => 'Saint Lucia',
                'phone_code' => 1758,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            185 =>
            array (
                'id' => 186,
                'code' => 'PM',
                'name' => 'Saint Pierre and Miquelon',
                'phone_code' => 508,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            186 =>
            array (
                'id' => 187,
                'code' => 'VC',
                'name' => 'Saint Vincent And The Grenadines',
                'phone_code' => 1784,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            187 =>
            array (
                'id' => 188,
                'code' => 'WS',
                'name' => 'Samoa',
                'phone_code' => 684,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            188 =>
            array (
                'id' => 189,
                'code' => 'SM',
                'name' => 'San Marino',
                'phone_code' => 378,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            189 =>
            array (
                'id' => 190,
                'code' => 'ST',
                'name' => 'Sao Tome and Principe',
                'phone_code' => 239,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            190 =>
            array (
                'id' => 191,
                'code' => 'SA',
                'name' => 'Saudi Arabia',
                'phone_code' => 966,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            191 =>
            array (
                'id' => 192,
                'code' => 'SN',
                'name' => 'Senegal',
                'phone_code' => 221,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            192 =>
            array (
                'id' => 193,
                'code' => 'RS',
                'name' => 'Serbia',
                'phone_code' => 381,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            193 =>
            array (
                'id' => 194,
                'code' => 'SC',
                'name' => 'Seychelles',
                'phone_code' => 248,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            194 =>
            array (
                'id' => 195,
                'code' => 'SL',
                'name' => 'Sierra Leone',
                'phone_code' => 232,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            195 =>
            array (
                'id' => 196,
                'code' => 'SG',
                'name' => 'Singapore',
                'phone_code' => 65,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            196 =>
            array (
                'id' => 197,
                'code' => 'SK',
                'name' => 'Slovakia',
                'phone_code' => 421,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            197 =>
            array (
                'id' => 198,
                'code' => 'SI',
                'name' => 'Slovenia',
                'phone_code' => 386,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            198 =>
            array (
                'id' => 199,
                'code' => 'XG',
                'name' => 'Smaller Territories of the UK',
                'phone_code' => 44,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            199 =>
            array (
                'id' => 200,
                'code' => 'SB',
                'name' => 'Solomon Islands',
                'phone_code' => 677,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            200 =>
            array (
                'id' => 201,
                'code' => 'SO',
                'name' => 'Somalia',
                'phone_code' => 252,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            201 =>
            array (
                'id' => 202,
                'code' => 'ZA',
                'name' => 'South Africa',
                'phone_code' => 27,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            202 =>
            array (
                'id' => 203,
                'code' => 'GS',
                'name' => 'South Georgia',
                'phone_code' => 0,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            203 =>
            array (
                'id' => 204,
                'code' => 'SS',
                'name' => 'South Sudan',
                'phone_code' => 211,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            204 =>
            array (
                'id' => 205,
                'code' => 'ES',
                'name' => 'Spain',
                'phone_code' => 34,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            205 =>
            array (
                'id' => 206,
                'code' => 'LK',
                'name' => 'Sri Lanka',
                'phone_code' => 94,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            206 =>
            array (
                'id' => 207,
                'code' => 'SD',
                'name' => 'Sudan',
                'phone_code' => 249,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            207 =>
            array (
                'id' => 208,
                'code' => 'SR',
                'name' => 'Suriname',
                'phone_code' => 597,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            208 =>
            array (
                'id' => 209,
                'code' => 'SJ',
                'name' => 'Svalbard And Jan Mayen Islands',
                'phone_code' => 47,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            209 =>
            array (
                'id' => 210,
                'code' => 'SZ',
                'name' => 'Swaziland',
                'phone_code' => 268,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            210 =>
            array (
                'id' => 211,
                'code' => 'SE',
                'name' => 'Sweden',
                'phone_code' => 46,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            211 =>
            array (
                'id' => 212,
                'code' => 'CH',
                'name' => 'Switzerland',
                'phone_code' => 41,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            212 =>
            array (
                'id' => 213,
                'code' => 'SY',
                'name' => 'Syria',
                'phone_code' => 963,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            213 =>
            array (
                'id' => 214,
                'code' => 'TW',
                'name' => 'Taiwan',
                'phone_code' => 886,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            214 =>
            array (
                'id' => 215,
                'code' => 'TJ',
                'name' => 'Tajikistan',
                'phone_code' => 992,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            215 =>
            array (
                'id' => 216,
                'code' => 'TZ',
                'name' => 'Tanzania',
                'phone_code' => 255,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            216 =>
            array (
                'id' => 217,
                'code' => 'TH',
                'name' => 'Thailand',
                'phone_code' => 66,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            217 =>
            array (
                'id' => 218,
                'code' => 'TG',
                'name' => 'Togo',
                'phone_code' => 228,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            218 =>
            array (
                'id' => 219,
                'code' => 'TK',
                'name' => 'Tokelau',
                'phone_code' => 690,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            219 =>
            array (
                'id' => 220,
                'code' => 'TO',
                'name' => 'Tonga',
                'phone_code' => 676,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            220 =>
            array (
                'id' => 221,
                'code' => 'TT',
                'name' => 'Trinidad And Tobago',
                'phone_code' => 1868,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            221 =>
            array (
                'id' => 222,
                'code' => 'TN',
                'name' => 'Tunisia',
                'phone_code' => 216,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            222 =>
            array (
                'id' => 223,
                'code' => 'TR',
                'name' => 'Turkey',
                'phone_code' => 90,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            223 =>
            array (
                'id' => 224,
                'code' => 'TM',
                'name' => 'Turkmenistan',
                'phone_code' => 7370,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            224 =>
            array (
                'id' => 225,
                'code' => 'TC',
                'name' => 'Turks And Caicos Islands',
                'phone_code' => 1649,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            225 =>
            array (
                'id' => 226,
                'code' => 'TV',
                'name' => 'Tuvalu',
                'phone_code' => 688,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            226 =>
            array (
                'id' => 227,
                'code' => 'UG',
                'name' => 'Uganda',
                'phone_code' => 256,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            227 =>
            array (
                'id' => 228,
                'code' => 'UA',
                'name' => 'Ukraine',
                'phone_code' => 380,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            228 =>
            array (
                'id' => 229,
                'code' => 'AE',
                'name' => 'United Arab Emirates',
                'phone_code' => 971,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            229 =>
            array (
                'id' => 230,
                'code' => 'GB',
                'name' => 'United Kingdom',
                'phone_code' => 44,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            230 =>
            array (
                'id' => 231,
                'code' => 'US',
                'name' => 'United States',
                'phone_code' => 1,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            231 =>
            array (
                'id' => 232,
                'code' => 'UM',
                'name' => 'United States Minor Outlying Islands',
                'phone_code' => 1,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            232 =>
            array (
                'id' => 233,
                'code' => 'UY',
                'name' => 'Uruguay',
                'phone_code' => 598,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            233 =>
            array (
                'id' => 234,
                'code' => 'UZ',
                'name' => 'Uzbekistan',
                'phone_code' => 998,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            234 =>
            array (
                'id' => 235,
                'code' => 'VU',
                'name' => 'Vanuatu',
                'phone_code' => 678,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            235 =>
            array (
                'id' => 236,
                'code' => 'VA',
            'name' => 'Vatican City State (Holy See)',
                'phone_code' => 39,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            236 =>
            array (
                'id' => 237,
                'code' => 'VE',
                'name' => 'Venezuela',
                'phone_code' => 58,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            237 =>
            array (
                'id' => 238,
                'code' => 'VN',
                'name' => 'Vietnam',
                'phone_code' => 84,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            238 =>
            array (
                'id' => 239,
                'code' => 'VG',
            'name' => 'Virgin Islands (British)',
                'phone_code' => 1284,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            239 =>
            array (
                'id' => 240,
                'code' => 'VI',
            'name' => 'Virgin Islands (US)',
                'phone_code' => 1340,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            240 =>
            array (
                'id' => 241,
                'code' => 'WF',
                'name' => 'Wallis And Futuna Islands',
                'phone_code' => 681,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            241 =>
            array (
                'id' => 242,
                'code' => 'EH',
                'name' => 'Western Sahara',
                'phone_code' => 212,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            242 =>
            array (
                'id' => 243,
                'code' => 'YE',
                'name' => 'Yemen',
                'phone_code' => 967,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            243 =>
            array (
                'id' => 244,
                'code' => 'YU',
                'name' => 'Yugoslavia',
                'phone_code' => 38,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            244 =>
            array (
                'id' => 245,
                'code' => 'ZM',
                'name' => 'Zambia',
                'phone_code' => 260,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            245 =>
            array (
                'id' => 246,
                'code' => 'ZW',
                'name' => 'Zimbabwe',
                'phone_code' => 263,
                'order' => NULL,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
    }
}
